### ISSUE TITLE
windows下编译失效

### ISSUE THREAD

**Issue by roytan883** [csr632/less-plugin-remove-antd-global-styles#2]
```
//windows下的斜杠和linux下不一样
      if (
        fullPath.includes('antd/es/style/core/global') ||
        fullPath.includes('antd/lib/style/core/global') ||
        fullPath.includes('antd\\es\\style\\core\\global') ||
        fullPath.includes('antd\\lib\\style\\core\\global')
      ) {
        return true
      }
```

**Comment by roytan883** [comment]
另外一个问题，仅pro模式有效，dev模式还是没有移除global.less，不清楚原因，我看了你的代码，没有判断环境呀，webpack有缓存？

**Comment by roytan883** [comment]
dev模式失效问题应该是webpack缓存的原因，插件开启屏蔽切换一下就好了。

**Comment by csr632** [comment]
Windows斜杠的问题，在代码中已经解决了：
https://github.com/csr632/less-plugin-remove-antd-global-styles/blob/b91ac679c71772bae8f9b4ddb57b3f11cb7f6709/src/index.ts#L28

所以这个问题不应该出现了。如果仍然存在的话，请提供一个复现仓库吧。

**Comment by csr632** [comment]
我写了一个在线Demo：
https://stackblitz.com/edit/webpack-5-react-starter-exaaw5?file=webpack.config.js

webpack dev模式是生效的。

**Comment by roytan883** [comment]
版本问题，因为https://npmmirror.com 中的是1.0.1，我更新了一下就好了
https://npmmirror.com/sync/less-plugin-remove-antd-global-styles
新版本发布以后，需要国内镜像刷新一下
